timezone: Europe/Warsaw
source: /

collections_config:
  pages:
    name: Strony
    path: "" # Szukaj w głównym katalogu
    output: true
    filter:
      base:
        - index.html # Skup się konkretnie na tym pliku
    _enabled_editors:
      - visual
      - source