timezone: Europe/Warsaw
source: /
# To mówi CloudCannonowi, że nie musi nic budować, pliki są gotowe:
ssg_name: static

collections_config:
  pages:
    name: Strony
    path: ""
    parser: html
    output: true
    _enabled_editors:
      - visual
      - source

# To aktywuje podgląd wizualny
_editables:
  content:
    active: true